# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181206_1613'),
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='createur',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
