# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projet', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='user.AppUser'),
        ),
    ]
