# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_auto_20181206_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projet',
            options={'get_latest_by': 'id', 'ordering': ['titre']},
        ),
    ]
