# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_auto_20190119_1429'),
        ('projet', '0003_auto_20190121_1319'),
    ]

    operations = [
    ]
