# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0004_merge_20190121_1619'),
        ('projet', '0004_merge_20190121_1444'),
    ]

    operations = [
    ]
