# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0006_projet_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
