# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='projet',
            field=models.CharField(default='nom du projet', max_length=50),
        ),
    ]
